# Generated by Django 6.0.4 on 2026-05-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollatzHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_number', models.IntegerField()),
                ('sequence', models.JSONField()),
                ('total_steps', models.IntegerField()),
                ('max_value', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Collatz Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
